name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hadolint (Dockerfile lint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Checkov (IaC scan)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform/
          framework: terraform

      - name: Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto

      - name: Trivy (CVE scan)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          exit-code: 1
          severity: CRITICAL
      - name: ZAP Baseline Scan (DAST)
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:30002'
          fail_action: false

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Cosign keyless sign
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign --yes myapp:latest
